import logging
from weasyprint import HTML

logger = logging.getLogger(__name__)

def generate_pdf_from_html(html_content: str) -> bytes | None:
    """Generate a PDF from raw HTML string using WeasyPrint."""
    try:
        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes
    except Exception as exc:
        logger.exception("generate_pdf_from_html failed: %s", exc)
        return None

def generate_rfq_pdf(requisition, supplier_name: str, items: list) -> bytes | None:
    """Generate Request for Quotation (RFQ) PDF."""
    from datetime import datetime as _dt, timezone as _tz
    
    date_str = _dt.now(_tz.utc).strftime("%B %d, %Y")
    rows_html = ""
    for idx, item in enumerate(items, 1):
        name = item.get("name", "")
        desc = item.get("description", "")
        qty = item.get("shortlisted_qty", item.get("qty", ""))
        rows_html += f"<tr><td>{idx}</td><td><b>{name}</b><br><small>{desc}</small></td><td style='text-align:center'>{qty}</td></tr>"

    html_content = f"""
    <!DOCTYPE html><html>
    <head><meta charset="utf-8">
    <style>@page{{margin:40px;}} body{{font-family:'Helvetica Neue',Arial,sans-serif;color:#1a1a1a;line-height:1.5;}}
    .wrap{{padding:20px;}}
    h1{{font-size:24px;border-bottom:2px solid #1a1a1a;padding-bottom:8px;margin-bottom:16px;text-align:center;}}
    table.meta{{width:100%;font-size:13px;margin-bottom:24px;}} table.meta td{{padding:4px 0;}}
    table.items{{border-collapse:collapse;width:100%;font-size:13px;margin-top:12px;}}
    table.items th{{border:1px solid #ccc;padding:8px;background:#f8fafc;font-size:12px;text-align:left;}}
    table.items td{{border:1px solid #ccc;padding:8px;}}
    .footer{{margin-top:32px;font-size:11px;color:#666;text-align:center;border-top:1px solid #eee;padding-top:16px;}}
    </style></head>
    <body><div class="wrap">
    <p style="text-align:right;font-size:12px;color:#666;margin-bottom:20px">Date: {date_str}</p>
    <h1>Request for Quotation (RFQ)</h1>
    <table class="meta">
    <tr><td width="15%"><b>To:</b></td><td>{supplier_name}</td></tr>
    <tr><td><b>Requisition:</b></td><td>{requisition.title}</td></tr>
    </table>
    
    <p style="font-size:14px;margin-bottom:16px;">Please provide your best quotation for the following items. Submit your quotation via the secure link provided in your email.</p>
    
    <table class="items">
    <thead><tr><th width="5%">#</th><th width="75%">Item Description</th><th width="20%" style="text-align:center">Requested Qty</th></tr></thead>
    <tbody>{rows_html}</tbody>
    </table>
    
    <p class="footer">This is an automated Request for Quotation generated by the Wener Supplier Management Platform.</p>
    </div></body></html>
    """
    return generate_pdf_from_html(html_content)
